sonar.projectKey=ERP_Saas
sonar.projectName=ERP_APP
sonar.projectVersion=1.0
sonar.sources=Backend,Frontend
sonar.inclusions=**/*.js,**/*.jsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.spec.js
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_366b0c91da02de75474dd18944548458311f0d99



